### ISSUE TITLE
Tune file upload chunk size based on file size

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/api_test#1]
We're using Evaporate.js to upload files to S3.  I believe we're using a small chunk size and it uploads in parallel, but it's a fixed size.  This may result in a huge number of uploaded chunks and it not being very efficient for large files.

I don't believe any chunk can be over 5GB and this is quite big if it needs to be resent because of an error.  On the other hand too small of chunk also can be annoying.

I suspect we can pick a larger chunk size or have the size vary based on the size of the file (maybe larger files get larger chunks so they don't get too huge a number).

**Comment by ahamelers** [comment]
Done in https://github.com/datadryad/dryad-app/pull/1581
